# Generated by Django 4.2.6 on 2023-10-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="resume",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="user",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
