# Generated by Django 4.2.6 on 2023-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(default="한국", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(default="서울", max_length=100),
            preserve_default=False,
        ),
    ]
